from typing import NamedTuple
from BaseClasses import ItemClassification


class ItemData(NamedTuple):
    name: str
    classification: ItemClassification
    count: int = 1


ITEMS = {
    'Axiom Disruptor': ItemData('Axiom Disruptor', ItemClassification.useful),
    'Nova': ItemData('Nova', ItemClassification.useful),
    'Multi-Disruptor': ItemData('Multi-Disruptor', ItemClassification.useful),
    'Kilver': ItemData('Kilver', ItemClassification.useful),
    'Firewall': ItemData('Firewall', ItemClassification.useful),
    'Hypo-Atomizer': ItemData('Hypo-Atomizer', ItemClassification.useful),
    'Voranj': ItemData('Voranj', ItemClassification.useful),
    'Reflector': ItemData('Reflector', ItemClassification.useful),
    'Inertial Pulse': ItemData('Inertial Pulse', ItemClassification.useful),
    'Orbital Discharge': ItemData('Orbital Discharge', ItemClassification.useful),
    'Lightning Gun': ItemData('Lightning Gun', ItemClassification.useful),
    'Turbine Pulse': ItemData('Turbine Pulse', ItemClassification.useful),
    'Shards': ItemData('Shards', ItemClassification.useful),
    'Distortion Field': ItemData('Distortion Field', ItemClassification.useful),
    'Data Bomb': ItemData('Data Bomb', ItemClassification.useful),
    'Tethered Charge': ItemData('Tethered Charge', ItemClassification.useful),
    'Quantum Variegator': ItemData('Quantum Variegator', ItemClassification.useful),
    'Ion Beam': ItemData('Ion Beam', ItemClassification.useful),
    'Reverse Slicer': ItemData('Reverse Slicer', ItemClassification.useful),
    'Flamethrower': ItemData('Flamethrower', ItemClassification.useful),
    'Heat Seeker': ItemData('Heat Seeker', ItemClassification.useful),
    'Scissor Beam': ItemData('Scissor Beam', ItemClassification.useful),
    'Fat Beam': ItemData('Fat Beam', ItemClassification.useful),
    'Laser Drill': ItemData('Laser Drill', ItemClassification.progression),
    'Sudran Key': ItemData('Sudran Key', ItemClassification.progression),
    'Field Disruptor': ItemData('Field Disruptor', ItemClassification.progression),
    'Lab Coat': ItemData('Lab Coat', ItemClassification.progression),
    'Trenchcoat': ItemData('Trenchcoat', ItemClassification.progression),
    'Red Coat': ItemData('Red Coat', ItemClassification.progression),
    'Remote Drone': ItemData('Remote Drone', ItemClassification.progression),
    'Drone Teleport': ItemData('Drone Teleport', ItemClassification.progression),
    'Address Disruptor 1': ItemData('Address Disruptor 1', ItemClassification.progression),
    'Address Disruptor 2': ItemData('Address Disruptor 2', ItemClassification.progression),
    'Address Bomb': ItemData('Address Bomb', ItemClassification.progression),
    'Grapple': ItemData('Grapple', ItemClassification.progression),
    'Passcode Tool': ItemData('Passcode Tool', ItemClassification.progression),
    'Enhanced Drone Launch': ItemData('Enhanced Drone Launch', ItemClassification.useful),
    'Bioflux Accelerator 1': ItemData('Bioflux Accelerator 1', ItemClassification.filler),
    'Bioflux Accelerator 2': ItemData('Bioflux Accelerator 2', ItemClassification.filler),
    'Health Node': ItemData('Health Node', ItemClassification.useful, count=9),
    'Power Node': ItemData('Power Node', ItemClassification.useful, count=6),
    'Health Node Fragment': ItemData('Health Node Fragment', ItemClassification.filler, count=20),
    'Power Node Fragment': ItemData('Power Node Fragment', ItemClassification.filler, count=18),
    'Size Node': ItemData('Size Node', ItemClassification.filler, count=4),
    'Range Node': ItemData('Range Node', ItemClassification.filler, count=4),
    'Note: Anonymous Quote': ItemData('Note: Anonymous Quote', ItemClassification.filler),
    'Faded Note': ItemData('Faded Note', ItemClassification.filler),
    'The Land of Civilized Kings': ItemData('The Land of Civilized Kings', ItemClassification.filler),
    'The Kuliltu': ItemData('The Kuliltu', ItemClassification.filler),
    'Oracca': ItemData('Oracca', ItemClassification.filler),
    'Proverb': ItemData('Proverb', ItemClassification.filler),
    'The Storm': ItemData('The Storm', ItemClassification.filler),
    'My Lovely': ItemData('My Lovely', ItemClassification.filler),
    'Athetos': ItemData('Athetos', ItemClassification.filler),
    'Security Notice': ItemData('Security Notice', ItemClassification.filler),
    'Official Letter': ItemData('Official Letter', ItemClassification.filler),
    'From the High Priestess': ItemData('From the High Priestess', ItemClassification.filler),
    'Public Notice': ItemData('Public Notice', ItemClassification.filler),
    'Plan B': ItemData('Plan B', ItemClassification.filler),
    'Journal Page (Xedur)': ItemData('Journal Page (Xedur)', ItemClassification.filler),
    'Transcription': ItemData('Transcription', ItemClassification.filler),
    'Journal Page (Uruku)': ItemData('Journal Page (Uruku)', ItemClassification.filler),
    'Axiom 1': ItemData('Axiom 1', ItemClassification.filler),
    'Sudran Translation': ItemData('Sudran Translation', ItemClassification.filler),
    'English': ItemData('English', ItemClassification.filler),
    'Letter': ItemData('Letter', ItemClassification.filler),
    'The Breach': ItemData('The Breach', ItemClassification.filler),
    'The Outsider': ItemData('The Outsider', ItemClassification.filler),
    'Reply: The Outsider': ItemData('Reply: The Outsider', ItemClassification.filler),
    'Journal Page (Breach Pockets)': ItemData('Journal Page (Breach Pockets)', ItemClassification.filler),
    'Trace': ItemData('Trace', ItemClassification.filler),
    'Vykhya Translation': ItemData('Vykhya Translation', ItemClassification.filler),
    'Drones': ItemData('Drones', ItemClassification.filler),
}

WEAPON_NAMES = {
    'Axiom Disruptor',
    'Nova',
    'Multi-Disruptor',
    'Kilver',
    'Firewall',
    'Hypo-Atomizer',
    'Voranj',
    'Reflector',
    'Inertial Pulse',
    'Orbital Discharge',
    'Lightning Gun',
    'Turbine Pulse',
    'Shards',
    'Distortion Field',
    'Data Bomb',
    'Tethered Charge',
    'Quantum Variegator',
    'Ion Beam',
    'Reverse Slicer',
    'Flamethrower',
    'Heat Seeker',
    'Scissor Beam',
    'Fat Beam',
}

NOVAISH_WEAPON_NAMES = {
    'Nova',
    'Hypo-Atomizer',
    'Reflector',
    'Orbital Discharge',
}

KILVERISH_WEAPON_NAMES = {
    'Kilver',
    'Distortion Field',
    'Reverse Slicer',
    'Flamethrower',
    'Scissor Beam',
    'Fat Beam',
}
